imageapp/urls.py
from django.urls import path

from .views import (
    ApprovePhotoListView,
    ListPhotosView,
    LikePhotoView,
    ApprovePhotoView,
    DeletePhotoView,
)

urlpatterns = [
    path("", ListPhotosView.as_view(), name="pictures"),
    path("like-picture", LikePhotoView.as_view(), name="like-picture"),
    path(
        "approve-picture", ApprovePhotoListView.as_view(), name="approve-picture-list"
    ),
    path(
        "approve-picture/<int:id>", ApprovePhotoView.as_view(), name="approve-pictures"
    ),
    path("delete-picture/<int:id>", DeletePhotoView.as_view(), name="delete-pictures"),
]

imagegallery/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include

urlpatterns = [
    path("", include(("imageapp.urls", "imageapp"), namespace="imageapp")),
    path("admin/", admin.site.urls),
    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

imageapp/models.py
from django.utils import timezone
from djongo import models


class Photo(models.Model):
    approved = models.BooleanField(default=False)
    date_taken = models.DateField(default=timezone.now)
    friends_name = models.CharField(max_length=150, null=False, blank=False)
    image_file = models.ImageField(null=True)
    likes = models.PositiveIntegerField(default=0, null=True, blank=True)

    def __str__(self):
        return f"{self.friends_name} - {self.date_taken}"

imageapp/forms.py
import datetime

from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile
from .models import Photo


class PhotoForm(forms.ModelForm):
    friends_name = forms.CharField(
        label="Image Name",
        widget=forms.TextInput(attrs={"class": "input-field col s12"}),
    )
    date_taken = forms.DateField(
        widget=forms.TextInput(
            attrs={"class": "datepicker", "type": "date", "placeholder": ""}
        )
    )

    def clean_friends_name(self):
        friends_name = self.cleaned_data["friends_name"]
        if friends_name.isnumeric():
            raise forms.ValidationError("Invalid name. Please provide a valid one.")
        return friends_name

    def clean_date_taken(self):
        date_taken = self.cleaned_data["date_taken"]
        if not isinstance(date_taken, datetime.date):
            raise forms.ValidationError("You need to provide a correct Date.")
        return date_taken

    def clean_image_file(self):
        image_file = self.cleaned_data["image_file"]
        if (
            not isinstance(image_file, InMemoryUploadedFile)
            or image_file.content_type != "image/jpeg"
        ):
            raise forms.ValidationError(
                "Incorrect type of image, only .JPG/.JPEG allowed."
            )
        return image_file

    class Meta:
        model = Photo
        fields = ["friends_name", "image_file", "date_taken"]

imageapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse

from django.views import View
from django.views.generic.edit import FormView, UpdateView, DeleteView
from django.views.generic.list import MultipleObjectMixin, ListView

from .forms import PhotoForm
from .models import Photo


class ListPhotosView(FormView, MultipleObjectMixin):
    form_class = PhotoForm
    template_name = "home_page.html"
    success_url = "/"
    paginate_by = 9

    def form_valid(self, form):
        if form.is_valid():
            form.save()
        return super(ListPhotosView, self).form_valid(form)

    def get_context_data(self, **kwargs):
        object_list = Photo.objects.filter(approved=True)
        order_param = self.request.GET.get("order")
        if order_param:
            object_list = object_list.order_by("-" + order_param)
        return super(ListPhotosView, self).get_context_data(
            object_list=object_list, **kwargs
        )


class ApprovePhotoListView(LoginRequiredMixin, ListView):
    login_url = "/login"
    model = Photo
    paginate_by = 6
    template_name = "imageapp/approve-image.html"

    def get_queryset(self):
        return Photo.objects.filter(approved=False)


class ApprovePhotoView(LoginRequiredMixin, UpdateView):
    fields = ["approved"]
    login_url = "/login"
    model = Photo
    success_url = "/approve-picture"

    def get_object(self):
        obj = Photo.objects.get(id=self.kwargs["id"])
        return obj

    def post(self, request, *args, **kwargs):
        try:
            photo = self.get_object()
            photo.approved = True
            photo.save()
            return super().post(request, *args, **kwargs)
        except Exception as exc:
            raise exc


class DeletePhotoView(LoginRequiredMixin, DeleteView):
    login_url = "/login"
    model = Photo
    success_url = "/approve-picture"

    def get_object(self):
        obj = Photo.objects.get(id=self.kwargs["id"])
        return obj


class LikePhotoView(View):
    def post(self, request):
        if request.is_ajax():
            photo_id = request.POST.get("image_id")
            photo = Photo.objects.filter(id=photo_id).first()
            if photo:
                photo.likes += 1
                photo.save()
                json_data = {"image": photo.id, "likes": photo.likes}
                return JsonResponse(json_data, status=200)
            return JsonResponse({"error": "Photo not found."}, status=400)
        return JsonResponse({"error": "Not allowed."}, status=400)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <!--Import Google Icon Font-->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://kit.fontawesome.com/8234b5de02.js"></script>
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
  </head>
  <body>
    {% include 'base/navbar.html' %}
    {% block content %}
    {% endblock %}

    <!-- JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
  </body>
</html>

templates/base/navbar.html
<nav class="z-depth-0 white">
  <div class="container">
    <div class="nav-wrapper">
      <a href="/" class="brand-logo center">Image Gallery</a>
      <a href="#" data-target="mobile-demo" class="sidenav-trigger">
        <i class="material-icons">menu</i>
      </a>
      <ul class="right hide-on-med-and-down">
        {% if request.user.is_authenticated %}
          <li><a href="{% url 'imageapp:approve-picture-list' %}" >Approve Images</a></li>
          <li><a href="{% url 'logout' %}">Logout</a></li>
        {% else %}
          <li><a href="{% url 'login' %}">Login</a></li>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

<ul class="sidenav" id="mobile-demo">
  {% if request.user.is_authenticated %}
    <li><a href="{% url 'imageapp:approve-picture-list' %}" >Approve Images</a></li>
    <li><a href="{% url 'logout' %}">Logout</a></li>
  {% else %}
    <li><a href="{% url 'login' %}">Login</a></li>
  {% endif %}
</ul>

templates/home_page.html
{% extends "base.html" %}

{% load static %}

{% block content %}
    <div class="container-fluid background-image">
        <div class="row">
            <form method="post" enctype="multipart/form-data">{% csrf_token %}
                <div class="col s3 offset-s1 input-box">
                    <h5 style="color: #767676"> Post our Photo </h5>
                    <div class="row">
                        <div class="input-field col s5">
                          <label for="friends_name">Your Name</label>
                          {{ form.friends_name}}
                          <small class="error-message">{{ form.friends_name.errors }}</small>
                        </div>
                         <div class="input-field col s6">
                          <label for="date_taken">Date Taken</label>
                          {{ form.date_taken }}
                          <small class="error-message" >{{ form.date_taken.errors }}</small>
                        </div>
                    </div>
                    <div class="row">
                         <div class="file-field col s11">
                          <div class="btn">
                            <span>File</span>
                            <input type="file" name="image_file">
                          </div>
                          <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                          </div>
                        <small class="error-message" >{{ form.image_file.errors }}</small>
                        </div>
                    </div>
                    <div class="row">
                        <div class="center" style="margin-top: 35px">
                            <button class="btn waves-effect waves-light center" type="submit" name="action">
                                Submit
                                <i class="material-icons right">send</i>
                            </button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="container-fluid">
        <h5 class="center"> Our Gallery </h5>
        <div class="row">
            <div class="col s12">
                <span> Order By </span>
                <a class="btn-small waves-effect waves-light center" href="?order=likes">
                    Likes
                </a>
                <a class="btn-small waves-effect waves-light center" href="?order=date_taken">
                    Date Taken
                </a>
            </div>
        </div>
        <div class="row">
            {% if object_list %}
                {% for image in object_list %}
                    <div class="col s6 m4">
                      <div class="card">
                        <div class="card-image">
                          <img  name="cardImage" id="{{ image.id }}" src="{{ image.image_file.url }}" width="100%" height="250">
                        </div>
                        <div class="valign-wrapper center">
                            <div class="col s4">
                              <p><i class="fas fa-user-friends"></i> {{ image.friends_name }}</p>
                            </div>
                            <div class="col s4">
                              <p><i class="far fa-calendar-alt"></i> {{ image.date_taken }}</p>
                            </div>
                            <div class="col s4">
                              <p><i class="far fa-heart"></i> <span id="like-{{image.id}}">{{ image.likes }}</span></p>
                            </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}
            {% else %}
                <h4 class="center"> No images to show... </h4>
            {% endif %}
        </div>
        {% if is_paginated %}
            <div class="container">
                <ul class="pagination">
                    {% if page_obj.has_previous %}
                        <li class="waves-effect">
                            <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                <i class="material-icons">chevron_left</i>
                            </a>
                        </li>
                    {% endif %}
                    {% for i in page_obj.paginator.page_range|slice:"0:4" %}
                        <li class="waves-effect {% if page_obj.number == i %}active{% endif %}">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}
                    {% if page_obj.paginator.num_pages > 8 %}
                        <li> . . . </li>
                    {% for i in page_obj.paginator.page_range|slice:"-4:" %}
                        <li class="waves-effect {% if page_obj.number == i %}active{% endif %}">
                            <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                        </li>
                    {% endfor %}
                    {% endif %}
                    {% if page_obj.has_next %}
                        <li class="waves-effect">
                            <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                <i class="material-icons">chevron_right</i>
                            </a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        {% endif %}
    </div>
{% endblock %}

templates/imageapp/approve-image.html
{% extends "base.html" %}

{% load static %}

{% block content %}

 <div class="container-fluid z-depth-2">
        <h5 class="center"> Approve Images </h5>
        <div class="row">
            {% if object_list %}
                {% for image in object_list %}
                    <div class="col s6 m4">
                      <div class="card">
                        <div class="card-image">
                          <img id="{{ image.id }}" src="{{ image.image_file.url }}" width="100%" height="250">
                        </div>
                        <div class="valign-wrapper center">
                            <div class="col s4">
                              <p><i class="fas fa-user-friends"></i> {{ image.friends_name }}</p>
                            </div>
                            <div class="col s4">
                              <p><i class="far fa-calendar-alt"></i> {{ image.date_taken }}</p>
                            </div>
                            <div class="col s4">
                              <p><i class="far fa-heart"></i> <span id="like-{{image.id}}">{{ image.likes }}</span></p>
                            </div>
                        </div>
                        <div class="card-action">
                            <div class="row center">
                                <div class="col s6">
                                    <form action="{% url 'imageapp:delete-pictures' image.id %}" method="POST" > {% csrf_token %}
                                        <div class="col s12">
                                            <button class="btn-flat" type="submit">
                                                <i class="material-icons center" style="color: red">clear</i>
                                            </button>
                                        </div>
                                    </form>
                                </div>
                                <div class="col s6">
                                    <form action="{% url 'imageapp:approve-pictures' image.id %}" method="POST" > {% csrf_token %}
                                            <div class="col s12">
                                                <button class="btn-flat" type="submit">
                                                    <i class="material-icons center" style="color: green">check</i>
                                                </button>
                                            </div>
                                            <input type="hidden" name="approved" value="true">
                                    </form>
                                </div>
                            </div>
                        </div>
                      </div>
                    </div>
                {% endfor %}
            {% else %}
                <h4 class="center"> No images to approve... </h4>
            {% endif %}
        </div>
        <div class="container">
            {% if is_paginated %}
                <div class="container">
                    <ul class="pagination">
                        {% if page_obj.has_previous %}
                            <li class="waves-effect">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <i class="material-icons">chevron_left</i>
                                </a>
                            </li>
                        {% endif %}
                        {% for i in page_obj.paginator.page_range|slice:"0:4" %}
                            <li class="waves-effect {% if page_obj.number == i %}active{% endif %}">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        {% if page_obj.paginator.num_pages > 8 %}
                            <li> . . . </li>
                        {% for i in page_obj.paginator.page_range|slice:"-4:" %}
                            <li class="waves-effect {% if page_obj.number == i %}active{% endif %}">
                                <a class="page-link" href="?page={{ i }}">{{ i }}</a>
                            </li>
                        {% endfor %}
                        {% endif %}
                        {% if page_obj.has_next %}
                            <li class="waves-effect">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <i class="material-icons">chevron_right</i>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                </div>
            {% endif %}
        </div>
        <br>
    </div>
{% endblock %}